package com.example.nice.everywhere.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.nice.everywhere.bean.BanmiDaoBean;

import com.example.nice.everywhere.dao.BanmiDaoBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig banmiDaoBeanDaoConfig;

    private final BanmiDaoBeanDao banmiDaoBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        banmiDaoBeanDaoConfig = daoConfigMap.get(BanmiDaoBeanDao.class).clone();
        banmiDaoBeanDaoConfig.initIdentityScope(type);

        banmiDaoBeanDao = new BanmiDaoBeanDao(banmiDaoBeanDaoConfig, this);

        registerDao(BanmiDaoBean.class, banmiDaoBeanDao);
    }
    
    public void clear() {
        banmiDaoBeanDaoConfig.clearIdentityScope();
    }

    public BanmiDaoBeanDao getBanmiDaoBeanDao() {
        return banmiDaoBeanDao;
    }

}
